version: "3.4"
services:
  app-openfire:
    image: "sir0liveira/openfire:latest"
    container_name: openfire
    hostname: localhost
    restart: unless-stopped
    tty: true
    ports:     
      - "5222:5222/tcp"
      - "5223:5223/tcp"
      - "5269:5269/tcp"
      - "7443:7443/tcp"
      - "9090:9090/tcp"
      - "9091:9091/tcp"
    volumes:
      - ./openfire:/var/lib/openfire
    networks:
      - my_net

  app-mysql:
    image: "mysql:latest"
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./openfire/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123@mudar
      MYSQL_DATABASE: openfire
      MYSQL_USER: openfire
      MYSQL_PASSWORD: openfire
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
